export const DOMAINS=['decathlon.es','decathlon.ro','pccomponentes.com','mediamarkt.es','leroymerlin.es','carrefour.es','ikea.com','bigbuy.eu','cjdropshipping.com','aliexpress.com','emag.ro','altex.ro'];
export function allowedUrl(value){let u;try{u=new URL(value);}catch{throw Error('Adresa produsului nu este validă.');}if(u.protocol!=='https:'||u.username||u.password||u.port||!DOMAINS.some(d=>u.hostname===d||u.hostname==='www.'+d))throw Error('Folosește o pagină HTTPS de la una dintre sursele acceptate.');return u;}
function clean(v,max=12000){return String(v??'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim().slice(0,max);}
function text(v){return clean(typeof v==='object'?v?.name??v?.value??'':v,400);}
function numeric(v){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null;}
function https(v,base){try{const u=new URL(typeof v==='object'?v?.url??v?.contentUrl:v,base);return u.protocol==='https:'&&!u.username&&!u.password&&!/^(localhost|127\.|10\.|192\.168\.|\[)/i.test(u.hostname)?u.href:'';}catch{return '';}}
function array(v){return v==null?[]:Array.isArray(v)?v:[v];}
function collect(node,out,depth=0){if(!node||typeof node!=='object'||depth>15||out.length>100)return;if(Array.isArray(node)){node.forEach(x=>collect(x,out,depth+1));return;}const types=array(node['@type']).map(t=>String(t).split('/').at(-1));if(types.includes('Product')||types.includes('ProductGroup'))out.push(node);for(const k of ['@graph','mainEntity','itemListElement','item','hasVariant'])collect(node[k],out,depth+1);}
export function extractProducts(html,url,checkedAt=new Date().toISOString()){
 const nodes=[];for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(!/type\s*=\s*["']application\/ld\+json["']/i.test(m[1]))continue;try{collect(JSON.parse(m[2]),nodes);}catch{}}
 return nodes.filter(p=>text(p.name)).slice(0,12).map(p=>{
  const offers=array(p.offers).flatMap(o=>o?.offers?array(o.offers):[o]).filter(o=>o&&typeof o==='object');const prices=offers.map(o=>({value:numeric(o.price??o.priceSpecification?.price??o.lowPrice),high:numeric(o.highPrice),currency:text(o.priceCurrency??o.priceSpecification?.priceCurrency).toUpperCase(),availability:text(o.availability).split('/').at(-1),url:https(o.url,url),seller:text(o.seller),shipping:array(o.shippingDetails).map(s=>({price:numeric(s.shippingRate?.value),currency:text(s.shippingRate?.currency),country:text(s.shippingDestination?.addressCountry),handling:JSON.stringify(s.deliveryTime?.handlingTime??null),transit:JSON.stringify(s.deliveryTime?.transitTime??null)}))})).filter(o=>o.value!==null);
  const currencies=[...new Set(prices.map(o=>o.currency))];const same=currencies.length===1&&currencies[0];const values=prices.flatMap(o=>[o.value,...(o.high!==null?[o.high]:[])]);const image=array(p.image).map(v=>https(v,url)).find(Boolean)||'';const attributes=['category','material','color','size','weight','width','height','depth'].map(k=>({name:k,value:text(p[k])})).filter(a=>a.value).concat(array(p.additionalProperty).map(a=>({name:text(a.name),value:text(a.value)})).filter(a=>a.name&&a.value));
  return {id:text(p.sku)||text(p.productID)||https(p.url,url)||url,title:text(p.name),description:clean(p.description),image,url:https(p.url,url)||url,sourceUrl:url,source:new URL(url).hostname,checkedAt,brand:text(p.brand),sku:text(p.sku),gtin:text(p.gtin??p.gtin13??p.gtin12??p.gtin14),category:text(p.category),attributes,offers:prices,price:same&&values.length?Math.min(...values):null,highPrice:same&&values.length?Math.max(...values):null,currency:same||'',availability:prices[0]?.availability||text(array(p.offers)[0]?.availability).split('/').at(-1),rating:numeric(p.aggregateRating?.ratingValue),reviewCount:numeric(p.aggregateRating?.reviewCount??p.aggregateRating?.ratingCount),variants:array(p.hasVariant).map(v=>({title:text(v.name),sku:text(v.sku),color:text(v.color),size:text(v.size)})).slice(0,20),evidence:'merchant-jsonld',salesKnown:false,dropshippingConfirmed:false,notice:'Date declarate de comerciant în pagina publică. Recenziile și prezența unei oferte nu dovedesc numărul de vânzări. Transportul și stocul trebuie reconfirmate pentru țara și varianta alese.'};
 });
}
export function rssLinks(xml){return [...new Set([...xml.matchAll(/<item\b[^>]*>[\s\S]*?<link>([\s\S]*?)<\/link>[\s\S]*?<\/item>/gi)].map(m=>m[1].replace(/^<!\[CDATA\[|\]\]>$/g,'').replace(/&amp;/g,'&').trim()))].filter(v=>{try{allowedUrl(v);return true;}catch{return false;}}).slice(0,8);}
export function shoppingProducts(data,checkedAt=new Date().toISOString()){
 return array(data.shopping_results).slice(0,12).filter(p=>p.title).map(p=>({id:String(p.product_id??p.product_link??p.title),title:clean(p.title,400),description:clean([p.snippet,...array(p.extensions)].filter(Boolean).join(' · ')),image:https(p.thumbnail),url:https(p.product_link??p.link),sourceUrl:https(p.product_link??p.link),source:clean(p.source,150),checkedAt,brand:'',sku:'',gtin:'',category:'',attributes:[],offers:[],price:numeric(p.extracted_price),highPrice:null,currency:/€|EUR/.test(String(p.price))?'EUR':/RON|lei/i.test(String(p.price))?'RON':'',priceText:clean(p.price,100),delivery:clean(p.delivery,300),rating:numeric(p.rating),reviewCount:numeric(p.reviews),variants:[],evidence:'shopping-search',salesKnown:false,dropshippingConfirmed:false,notice:'Ofertă din rezultatele Google Shopping. Poate fi preț de magazin, nu de furnizor. Nu dovedește vânzări sau livrare dropshipping.'})).filter(p=>p.url);
}
export async function readPage(url,fetcher=fetch){let u=allowedUrl(url);const signal=AbortSignal.timeout(8500);for(let i=0;i<4;i++){const r=await fetcher(u.href,{redirect:'manual',signal,headers:{Accept:'text/html','User-Agent':'ComertStudio/0.2 (+product-research; public metadata)'}});if(r.status>=300&&r.status<400){u=allowedUrl(new URL(r.headers.get('location'),u).href);continue;}if(!r.ok)throw Error('Comerciantul răspunde HTTP '+r.status);if(!/text\/html/i.test(r.headers.get('content-type')??''))throw Error('Pagina nu este HTML');if(Number(r.headers.get('content-length'))>3e6)throw Error('Pagina depășește limita de citire');let size=0,parts=[];for await(const b of r.body){size+=b.byteLength;if(size>3e6){throw Error('Pagina depășește limita de citire');}parts.push(b);}const html=Buffer.concat(parts).toString('utf8');const products=extractProducts(html,u.href);if(!products.length)throw Error('Pagina nu publică o fișă Product JSON-LD lizibilă. Nu am inventat prețuri sau descrieri.');return products;}throw Error('Prea multe redirecționări');}
